### PR TITLE
migration to null-safety Fix #5

### LINKED ISSUE #5: update to null-safety

### PR DESCRIPTION
**Pull request by justkawal**
Migration to null-safety done

🙇‍♂️🚀💯 Tested ✅

### CODE REVIEW

**Comment by alexshikov** [comment]
Looking forward to merging it...

**Comment by justkawal** [comment]
@alexshikov Yes, It's working here

**Comment by alexshikov** [comment]
hi @pikaju, are there any plans to accept this PR?

**Comment by pikaju** [comment]
Sure, thank you! Sorry for the wait guys.

**Pull request merged**
